FROM node:carbon
WORKDIR /home/jeddai/star-wars-5e
COPY package*.json ./
RUN npm install --only=production
RUN npm run build-prod
COPY . .
COPY /etc/letsencrypt/live/dnd.jeddai.com/cert.pem .
COPY /etc/letsencrypt/live/dnd.jeddai.com/privkey.pem .
EXPOSE 443
CMD ["PORT=443", "ENV=prod", "npm", "start"]